In [2]:
import numpy as np

In [2]:
vector_row=np.array([12,56,89,63])
print(vector_row)

[12 56 89 63]


In [3]:
#vector column
vector_column=np.array([[1],
                        [2],
                        [3]])
print(vector_column)

[[1]
 [2]
 [3]]


In [5]:
#changing datatyoe
vector=np.array([15,43,67,89])
print(vector)
print(vector.dtype)
vector=np.array([12,34,56],dtype="float")
print(vector)

[15 43 67 89]
int32
[12. 34. 56.]


In [6]:
#Creating the sequence of numbers using arange(start, stop,step) function
a=np.arange(start=10,stop=21)
print(a)

[10 11 12 13 14 15 16 17 18 19 20]


In [11]:
a=np.arange(start=2,stop=21,step=2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [18]:
#Indexing and Selection of array element using index and slicing operation
a=np.arange(start=1,stop=11)
print(a)
print(a[0])
print(a[5])
print(a[-5])
print(a[2::])
print(a[2:10:])
print(a[1:10:2])

[ 1  2  3  4  5  6  7  8  9 10]
1
6
6
[ 3  4  5  6  7  8  9 10]
[ 3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


In [24]:
#resize
a=np.arange(start=1,stop=11)
print(a)
a.resize(2,5)
print(a)
a=np.arange(start=1,stop=13)
print(a)
a.resize(3,4)
print(a)
a.resize(4,3)
print(a)
a.resize(6,2)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [3]:
# To find shape of matrix  using shape 
m = np.array([[[10,20,30],[10,20,40]],[[50,60,70],[30,76,45]]])
print(m)
m.shape

[[[10 20 30]
  [10 20 40]]

 [[50 60 70]
  [30 76 45]]]


(2, 2, 3)

# two or multidimensional array

In [29]:
#to create multidimensional array
a=np.array([[10,67,89],[54,32,87]])
print(a)
a.ndim


[[10 67 89]
 [54 32 87]]


2

In [30]:
a.size

6

In [31]:
a.shape

(2, 3)

In [35]:
# Create two dimensional array or matrix using arange()
matrix=np.arange(start=1,stop=13)
print(matrix)
matrix.resize(4,3)
print(matrix)
print(matrix[0][2])
print(matrix[2][0])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
3
7


In [45]:
#Creating Zero Matrix using zeros()
m=np.zeros((3,4))
print(m)
m=np.zeros((3,4),dtype="int")
print(m)
#creating ones matrix using ones()
n=np.ones((3,4))
print(n)
n=np.ones((3,4),dtype="int")
print(n)
#creating identity matrix using eye()
a=np.eye(4)
print(a)
a=np.eye(4,dtype="int")
print(a)
#creating diagonal matrix using diag()
a=np.diag([12,56,87,90])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[12  0  0  0]
 [ 0 56  0  0]
 [ 0  0 87  0]
 [ 0  0  0 90]]


In [48]:
#Creating sample space using linspace() bydefault 50
a=np.linspace(start=1,stop=20)
print(a)
a.size
a=np.linspace(start=1,stop=20,num=20)
print(a)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]


In [47]:
from numpy import random
sample=random.rand()
print(sample)
sample=random.rand(5)
print(sample)
sample=random.randint(100,size=(3,4))
print(sample)
sample=random.randint(70,100,size=(3,4))
print(sample)
sample=random.choice([5,6,7])
print(sample)
sample=random.choice([5,6,7],size=(3,4))
print(sample)

0.2183361780939651
[0.85909038 0.20871788 0.29022443 0.22082276 0.15438554]
[[23 20  8 16]
 [21 69 32 64]
 [85 83 86 42]]
[[71 80 89 74]
 [91 99 97 83]
 [72 71 73 99]]
6
[[7 5 5 5]
 [6 7 5 7]
 [7 6 5 7]]


In [49]:
from numpy import random
m=random.choice([5,6,8,3],p=[0.1,0.4,0.3,0.2],size=100)
print(m)


[6 3 8 3 6 8 6 6 3 8 8 3 5 5 6 6 3 6 8 6 5 3 3 8 6 6 6 3 5 8 3 3 6 5 3 6 3
 8 6 8 5 8 3 6 6 3 6 6 6 6 8 6 3 6 3 8 3 8 3 8 8 6 6 3 8 6 6 8 6 6 6 8 6 8
 8 8 6 3 8 3 6 6 5 5 3 6 3 8 8 3 6 6 5 8 6 6 6 3 3 6]


In [50]:
c5=0
c6=0
c8=0
c3=0
for i in m:
    if i==5:
        c5+=1
    elif i==6:
        c6+=1
    elif i==8:
        c8+=1
    else:
        c3+=1
print(c5,c6,c8,c3)

9 40 25 26


In [55]:
# To find the sum, minimum, maximum, mean, standard deviation and variance 
a=np.arange(start=1,stop=13)
a.resize((3,4))
print(a)
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.var())
print(a.argmin())
print(a.argmax())


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
1
12
6.5
3.452052529534663
11.916666666666666
0
11


# numpy operation

In [93]:
a=np.arange(start=1,stop=7)
a.resize(2,3)
print(a)
b=np.arange(start=11,stop=17)
b.resize(2,3)
print(b)
c=np.add(a,b)
print(c)
c=np.subtract(b,a)
print(c)
c=np.multiply(a,b)
print(c)
c=np.divide(a,b)
print(c)
c=np.add(a,b)
print(c)
c=np.power(a,3)
print(c)
c=np.mod(a,2)
print(c)
c=np.remainder(a,3)
print(c)
c=np.divmod(a,4)
print(c)
d=np.absolute(a)
print(d)
d=np.around(7.9)
print(d)
d=np.floor(7.9)
print(d)
c=np.sum(a)
print(c)
c=np.diff(a)
print(c)
c=np.prod(a)
print(c)
c=np.cumsum(a)
print(c)
c=np.cumprod(a)
print(c)
c=np.lcm(a,b)
print(c)
c=np.gcd(a,b)
print(c)
c=np.add(a,b)
print(c)
c=np.sin(90)
print(c)
c=np.cos(0)
print(c)
c=np.tan(45)
print(c)
c=np.deg2rand(90)
print(c)
c=np.rand2deg(0.567)
print(c)












[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]
[[12 14 16]
 [18 20 22]]
[[10 10 10]
 [10 10 10]]
[[11 24 39]
 [56 75 96]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]]
[[12 14 16]
 [18 20 22]]
[[  1   8  27]
 [ 64 125 216]]
[[1 0 1]
 [0 1 0]]
[[1 2 0]
 [1 2 0]]
(array([[0, 0, 0],
       [1, 1, 1]], dtype=int32), array([[1, 2, 3],
       [0, 1, 2]], dtype=int32))
[[1 2 3]
 [4 5 6]]
8.0
7.0
21
[[1 1]
 [1 1]]
720
[ 1  3  6 10 15 21]
[  1   2   6  24 120 720]
[[11 12 39]
 [28 15 48]]
[[1 2 1]
 [2 5 2]]
[[12 14 16]
 [18 20 22]]
0.8939966636005579
1.0
1.6197751905438615


AttributeError: module 'numpy' has no attribute 'deg2rand'

In [98]:
import numpy as np
s={1,2,3,2,4,5,8}
d={3,4,7,9,1,5,8}
a=np.unique(s,d)
print(a)

(array([{1, 2, 3, 4, 5, 8}], dtype=object), array([0], dtype=int64))


1)HOW TO CREATE A ROW AND COLUMN
2)HOW TO CHANGED DAATATYPE USING DTYPE="" FUNCTION
3)NP.RESHAPE() FUNCTION
4)NP.RESIZE(N0.OF ROW,N. OF COLUMN) FUNCTION
5)NP.ARANGE(START,STOP,STEP)
6)NP.ZEROS() FUNCTION TO CRAETE ZERO MATRIX(DEFALUT VALUE IS IN FLOAT)
7)NP.ONES() FUNCTION TO CREATE ONE MATRIX(DEFAULT VALUE IS IN FLOAT)
8)NP.EYE() FUNCTION TO CREATE IDENTITY MATRIX(DEFAULT VALUE IS IN FLOAT)
9)NP.DIAG([ELEMENT IN THE LIST]) FUNCTION TO CREATE THE DIAGONAL MATRIX
10)CREATING SAMPLE SPACE USING LINSPACE(START,STOP)
11)TO GIVE THE RANDOM FUNCTION:FROM NUMPY IMPORT RANDOM
SAMPLE=RANDOM.RAND(5)
12)NUMPY OPERATION

1)get the version and show the numpy build configuration

In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


add function using numpy

In [4]:
np.add(1,4)


5

In [5]:
np.add(10.9,12.0)

22.9

test whether none of the elements of a given array is zero

In [7]:
import numpy as np
x=np.array([1,2,3,4])
print("original array is:",x)
print("whether zero is present or not:")
print(np.all(x))
y=np.array([0,2,3,5])
print("original array is:",y)
print("the zero is present or not:")
print(np.all(y))


original array is: [1 2 3 4]
whether zero is present or not:
True
original array is: [0 2 3 5]
the zero is present or not:
False


to find non-zero element in the array

In [9]:
import numpy as np
x=np.array([1,0,0,0])
print("original array is:",x)
print("non-zero element is present or not:")
print(np.any(x))
y=np.array([0,0,0,0])
print("original array is:",y)
print("non-zero element is present or not:")
print(np.any(y))

original array is: [1 0 0 0]
non-zero element is present or not:
True
original array is: [0 0 0 0]
non-zero element is present or not:
False


In [11]:
#find finiteness
import numpy as np
x=np.array([1,0,np.nan,np.inf])
print("original array is:",x)
print("is the entered array is a finnite or not:")
print(np.isfinite(x))

original array is: [ 1.  0. nan inf]
is the entered array is a finnite or not:
[ True  True False False]


In [13]:
#nan value
import numpy as np
x=np.array([1,0,np.nan,np.inf])
print("original array is:",x)
print("nan is present or not:")
print(np.isnan(x))

original array is: [ 1.  0. nan inf]
nan is present or not:
[False False  True False]


In [14]:
#check complex,real,scalar or not
import numpy as np
x=np.array([1+1j,1+0j,4.5,3,2,2j])
print("original array is:",x)
print("complex number :")
print(np.iscomplex(x))
print("real number:")
print(np.isreal(x))
print(np.isscalar(3.1))


original array is: [1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
complex number :
[ True False False False False  True]
real number:
[False  True  True  True  True False]
True


In [15]:
#find the greater,greater equal,lesser,lesser equal between tthe two array
import numpy as np
x=np.array([3,5])
y=np.array([2,5])
print("original numbers:")
print(x,y)
print("comparison-greater:")
print(np.greater(x,y))
print("comparison-greater equal:")
print(np.greater_equal(x,y))
print("comparision-lesser:")
print(np.less(x,y))
print("comparision-lesser equal:")
print(np.less_equal(x,y))


original numbers:
[3 5] [2 5]
comparison-greater:
[ True False]
comparison-greater equal:
[ True  True]
comparision-lesser:
[False False]
comparision-lesser equal:
[False  True]


In [18]:
#comparision equal,equal within a tolerance
import numpy as np
x=np.array([72,79,85,90,150,-135,120,-10,60,100])
y=np.array([72,79,85,90,150,-135,120,-10,60,100.0001])
print("original array is:")
print(x,"\n",y)
print("comparision-equal:")
print(np.equal(x,y))
print("comparision-equal within the tolerance:")
print(np.allclose(x,y))

original array is:
[  72   79   85   90  150 -135  120  -10   60  100] 
 [  72.       79.       85.       90.      150.     -135.      120.
  -10.       60.      100.0001]
comparision-equal:
[ True  True  True  True  True  True  True  True  True False]
comparision-equal within the tolerance:
True


In [22]:
#determine the size
import numpy as np
x=np.array([1,7,13,105])
print("original array is:",x)
print("memory size is:")
#print(np.size(x))#these is the size of array
print("%d BYTES" %(x.size*x.itemsize))

original array is: [  1   7  13 105]
memory size is:
16 BYTES


In [7]:
#array of 10 zeros,10 ones,10 fives
import numpy as np
m=np.zeros(10)
print(m)
m=np.ones(10)
print(m)
m=np.ones(10)*5

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64


TypeError: array() missing required argument 'object' (pos 1)

In [8]:
#create an array from 30 to 70
m=np.arange(start=30,stop=71)
print(m)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [9]:
#create an array to print all even integer from 30 to 70
m=np.arange(start=30,stop=71,step=2)
print(m)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [13]:
#create 3*3 identity matrix
m=np.eye(3,3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
from numpy import random
m=np.random.normal(0,1,1)
print(m)

[0.09022323]


In [20]:
#array of 15 random number from a standard normal distribution
m=np.random.normal(0,1,15)
print(m)

[ 0.89538168  0.3221337   0.34895681  0.60601117  0.74016291 -0.30175642
 -1.18729827 -2.4409879   0.85126163  0.20295585  0.25714164 -0.78472493
  0.68730356  0.77564683 -0.03454967]


In [34]:
#create a vector from 15 to 55 and print values except first and last
m=np.arange(start=15,stop=56)
print(m[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [35]:
#create an 3*4 matrix and iterate it
m=np.arange(10,22).reshape((3,4))
print(m)
print('each element in the matrix is:')
for i in np.nditer(m):
    print(i,end=' ')

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
each element in the matrix is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [41]:
#array between 0 to 20 and change the sign of number in range 9 to 15
m=np.arange(start=0,stop=21)
m[(m>=9) & (m<=15)] *=-1
print(m)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [42]:
#program to create vector of length 5 from integer 0 to 10
m=np.random.randint(0,11,5)
print(m)


[ 8  6 10  1  7]


In [43]:
#multiply values of two given vector/matrix
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)
print(b)
c=np.multiply(a,b)
print(c)

[1 2 3 4]
[5 6 7 8]
[ 5 12 21 32]


In [46]:
#create 3*4 matrix filled with value from 10 to 21
m=np.arange(start=10,stop=22)
m.resize(3,4)
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [50]:
#find no. of rows and no. of col in givven matrix
m=np.array([[1,2,3],[8,9,7],[6,5,4],[4,3,2]])
np.shape(m)

(4, 3)

In [53]:
#creattte 10*10 matrix in which border are 1 and inside 0
m=np.ones((10,10))
m[1:-1,1:-1]=0
print(m)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [54]:
#create 5*5 matrix with diagonal qual to 1,2,3,4,5
m=np.diag([1,2,3,4,5])
print(m)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
