### What is Numpy:
1. NumPy (acronym for 'Numerical Python' or 'Numeric Python') 
2. It is one of the most essential package for speedy mathematical computation 
on arrays and matrices in Python. 
3. It is also quite useful while dealing with multi-dimensional data. 
4. It also provides numerous functions for Fourier transform (FT) and linear algebra.

In [8]:
#Importing numpy
import numpy as np

### One Dimensional Array or Vector

In [9]:
# Create one dimensional array or row or row vector
vector_row = np.array([15,25,14,78,96])
print(vector_row)

[15 25 14 78 96]


In [3]:
## Create one dimensional array or coloumn or coloumn vector
vector_column = np.array([[1],
                          [2],
                          [3]])
print(vector_column)

[[1]
 [2]
 [3]]


In [8]:
#Changing the datatype
vector_row = np.array([15,25,14,78,96])
print(vector_row)
print(vector_row.dtype)
vector_row = np.array([15,25,14,78,96],dtype = "float")
print(vector_row)
print(vector_row.dtype)

[15 25 14 78 96]
int32
[15. 25. 14. 78. 96.]
float64


In [13]:
#Creating the sequence of numbers using arange(start, stop,step) function
a = np.arange(start=10,stop=21)
print(a)

[10 11 12 13 14 15 16 17 18 19 20]


In [14]:
#Creating the sequence of numbers using arange(start, stop,step) function
a = np.arange(start=10,stop=21,step=2)
print(a)

[10 12 14 16 18 20]


In [23]:
#Indexing and Selection of array element using index and slicing operation
a=np.arange(start=10,stop=20)
print(a)
print(a[4])
print(a[-4])
print(a[2::])
print(a[2:10:])
print(a[2:10:3])

[10 11 12 13 14 15 16 17 18 19]
14
16
[12 13 14 15 16 17 18 19]
[12 13 14 15 16 17 18 19]
[12 15 18]


In [28]:
# reshape(): It used to reshape the array
a = np.arange(start=1,stop=13)
print(a)
a.reshape(2,6)
print(a)
a.reshape(3,4)
print(a)
a.reshape(4,3)
print(a)
a.reshape(6,2)
print(a)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


Note: that reshape() does not alter the shape of the original array. 
Thus to modify the original array we can use resize( )

In [29]:
# resize(): It used to resize the array
a = np.arange(start=1,stop=13)
print(a)
a.resize(2,6)
print(a)
a.resize(3,4)
print(a)
a.resize(4,3)
print(a)
a.resize(6,2)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


### Two or Multi Dimensional Array or Matrix

In [30]:
# Create two dimensional array or matrix 
matrix = np.array([[10,20,30],[40,50,60]])
print(matrix)

[[10 20 30]
 [40 50 60]]


In [2]:
# To find the dimension of matrix using ndim() function
import numpy as np
m = np.array([[10,20,30],[40,50,60]])
print(m)
print(np.ndim(m))

[[10 20 30]
 [40 50 60]]
2


In [4]:
# To find the number of element in matrix or size of matrix using size 
m = np.array([[10,20,30],[40,50,60]])
print(m)
np.size(m)

[[10 20 30]
 [40 50 60]]


6

In [3]:
# To find shape of matrix  using shape 
m = np.array([[10,20,30],[40,50,60]])
print(m)
np.shape(m)

[[10 20 30]
 [40 50 60]]


(2, 3)

In [6]:
# Create two dimensional array or matrix using arange()
matrix = np.arange(start=1,stop=13)
print(matrix)
matrix.resize(3,4)
print(matrix)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
# Create two dimensional array or matrix using arange()
matrix = np.arange(start=1,stop=13)
print(matrix)
matrix.reshape(4,3)
print(matrix)
matrix.resize(4,3)
print(matrix)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [49]:
# Indexing and Selection of two dimensional element of matrix
matrix = np.arange(start=1,stop=13)
print(matrix)
matrix.resize(4,3)
print(matrix)
print(matrix[0][2])
print(matrix[2][1])


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
3
8


In [57]:
#Creating Zero Matrix using zeros()
m=np.zeros((3,4))
print(m)
print("Note: Bydefault It is in float type")
m=np.zeros((3,4), dtype=int)
print(m)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Note: Bydefault It is in float type
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [58]:
#Creating Zero Matrix using ones()
m=np.ones((3,4))
print(m)
print("Note: Bydefault It is in float type")
m=np.ones((3,4), dtype=int)
print(m)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Note: Bydefault It is in float type
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [62]:
#Creating Identity Matrix using eyes()
m=np.eye(4)
print(m)
print("Note: Bydefault It is in float type")
m=np.eye(4, dtype=int)
print(m)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Note: Bydefault It is in float type
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [65]:
#Creating Diagonal Matrix using diag()
m=np.diag([15,12,14,16])
print(m)
print("Note: Bydefault It is in float type")
m=np.diag([15,12,14,16])
print(m)

[[15  0  0  0]
 [ 0 12  0  0]
 [ 0  0 14  0]
 [ 0  0  0 16]]
Note: Bydefault It is in float type
[[15  0  0  0]
 [ 0 12  0  0]
 [ 0  0 14  0]
 [ 0  0  0 16]]


In [75]:
#Creating sample space using linspace() bydefault 50
m=np.linspace(start=10,stop=20)
print(m)
m.size


[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


50

In [74]:
m=np.linspace(start=10,stop=20,num=20)
print(m)

[10.         10.52631579 11.05263158 11.57894737 12.10526316 12.63157895
 13.15789474 13.68421053 14.21052632 14.73684211 15.26315789 15.78947368
 16.31578947 16.84210526 17.36842105 17.89473684 18.42105263 18.94736842
 19.47368421 20.        ]


In [17]:
#Creating sample space using random() 
from numpy import random
sample=random.rand()
print(sample)
sample=random.rand(5)
print(sample)
sample=random.rand(2,5)
print(sample)
sample=random.randint(100,size=(3,4))
print(sample)
sample=random.randint(70,100,size=(3,4))
print(sample)
sample=random.choice([5,6,8])
print(sample)
sample=random.choice([5,6,8],size=(3,4))
print(sample)

0.007240434747672553
[0.61286797 0.33304249 0.98437379 0.63930561 0.99050226]
[[0.89261703 0.69440555 0.78692718 0.50124213 0.24066531]
 [0.115122   0.33145347 0.3585654  0.28668938 0.5508722 ]]
[[40 93 79 55]
 [86 84 86 84]
 [57 39 88 19]]
[[89 84 82 74]
 [88 93 81 73]
 [92 93 97 89]]
8
[[6 8 8 8]
 [5 5 8 5]
 [5 8 5 5]]


In [19]:
from numpy import random
sample=random.choice([5,6,8,3],p=[0.1,0.4,0.3,0.2],size=300)
print(sample)      

[6 8 5 6 8 3 8 6 8 5 6 8 6 5 5 5 6 8 8 3 6 6 8 3 3 6 6 8 5 8 3 6 8 8 6 6 6
 6 6 8 3 6 8 3 6 8 3 6 3 5 8 6 6 6 6 6 8 6 8 8 3 8 6 3 6 8 6 8 5 3 8 6 8 8
 5 8 3 3 6 6 3 8 6 6 8 6 5 6 8 6 8 6 5 3 3 6 8 6 3 6 8 6 8 6 8 3 3 5 6 8 6
 6 6 5 3 3 6 5 6 6 3 6 8 3 8 6 6 5 6 8 3 8 8 8 6 6 5 8 8 8 6 8 6 6 5 6 8 8
 5 3 6 8 8 8 3 6 5 3 3 8 6 6 8 6 8 8 8 8 5 5 6 6 8 6 5 6 8 6 6 8 3 5 8 8 8
 6 3 6 6 6 8 3 6 6 8 8 8 6 8 6 6 6 6 8 6 8 8 6 3 3 6 8 6 6 6 6 6 8 6 6 3 8
 5 8 6 5 3 3 3 6 8 6 6 8 3 6 6 3 6 8 8 5 6 6 3 3 3 8 6 6 3 6 6 8 8 6 6 8 6
 8 6 6 8 6 3 6 8 8 3 8 8 8 3 6 5 8 3 6 6 8 3 8 6 6 6 6 6 6 5 8 6 8 3 8 6 6
 6 8 8 6]


In [100]:
c5=0
c6=0
c8=0
c3=0
for i in sample:
    if i==5:
        c5+=1
    if i==6:
        c6+=1
    if i==8:
        c8+=1
    if i==3:
        c3+=1
print(c5,c6,c8,c3)

8 36 34 22


In [109]:
# To find the sum, minimum, maximum, mean, standard deviation and variance 
m = np.arange(start=1,stop=13)
m.resize((3,4))
print(m)
print(m.sum())
print(m.min())
print(m.max())
print(m.std())
print(m.var())
print(m.argmin())#minimum index value
print(m.argmax())#maximum index value


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
78
1
12
3.452052529534663
11.916666666666666
11.916666666666666
0
11


In [20]:
from numpy import random
sample=random.choice([5,6,8,3],p=[0.1,0.4,0.3,0.2],size=300)
print(sample)

[3 8 8 6 6 6 8 8 6 6 5 6 6 6 8 3 3 6 8 5 3 8 3 6 5 6 6 6 6 8 3 8 6 6 6 3 8
 8 6 8 3 6 3 8 3 8 6 6 6 6 6 8 6 6 8 3 5 5 6 6 8 5 3 3 8 6 8 3 6 3 6 6 5 6
 6 8 6 8 6 3 6 3 6 3 6 6 6 5 8 8 5 6 8 8 6 8 8 8 6 3 6 6 3 8 6 6 3 8 6 5 8
 3 6 8 6 8 8 8 8 8 5 6 6 8 5 8 3 6 3 6 8 6 8 6 8 6 6 6 8 8 6 6 6 8 6 5 6 6
 8 8 6 6 5 6 6 6 6 6 8 8 8 6 8 6 6 3 6 6 3 6 6 3 3 6 8 6 8 6 8 6 3 8 6 6 8
 6 8 6 3 6 5 3 8 8 6 3 6 6 8 6 3 5 3 3 8 5 8 8 3 8 6 3 6 8 5 6 6 6 8 8 3 5
 8 8 8 5 5 5 8 8 6 5 6 8 6 6 5 6 3 6 6 8 5 8 6 6 6 3 5 3 6 8 3 8 6 8 8 6 5
 6 6 8 6 8 5 8 8 8 6 8 6 3 6 5 8 3 3 6 6 5 3 8 6 6 6 3 6 8 3 3 3 6 3 3 3 6
 3 6 3 6]


### Numpy Operation

In [ ]:
from numpy import random
sample=random.choice([5,6,8,3],p=[0.1,0.4,0.3,0.2],size=300)
print(sample)


# assignment 1
# numpy function
1)add()
2)substract()
3)multiply()
4)divide()
5)power()
6)mod()
7)remainder()
8)divmod()
9)absolute()
10)around()
11)floor()
12)cell()
13)sum()
14)csum()
15)prod()
16)cumprod()
17)diff()
18)lcm()
19)gcd()
20)sin(),cos(),tan()
21)deg2rad()
22)rad2deg()
23)hypot()
24)unique()
25)unionid()#
26)intersectionid()




In [38]:
#here we have to take the array
import numpy as np
a=np.add(2,3)
print(a)
a=np.subtract(9,5)
print(a)
a=np.multiply(9,5)
print(a)
a=np.divide(9,5)
print(a)
a=np.power(4,2)
print(a)
a=np.mod(9,5)
print(a)
a=np.remainder(9,5)
print(a)
a=np.divmod(9,5)
print(a)
a=np.absolute(5.9)
print(a)
a=np.around(9.5)
print(a)
a=np.floor(9.5)
print(a)
a=np.array([5,6])
b=np.sum(a)
print(b)
b=np.diff(a)
print(b)
b=np.prod(a)
print(b)
b=np.cumprod(a)
print(b)
b=np.cumsum(a)
print(b)
b=np.lcm(3,4)
print(b)
b=np.gcd(5,6)
print(b)
b=np.sin(60)
print(b)
b=np.cos(30)
print(b)
b=np.tan(45)
print(b)
b=np.deg2rand(30)
print(b)

5
4
45
1.8
16
4
4
(1, 4)
5.9
10.0
9.0
11
[1]
30
[ 5 30]
[ 5 11]
12
1
-0.3048106211022167
0.15425144988758405
1.6197751905438615


AttributeError: module 'numpy' has no attribute 'deg2rand'